version: 2.1
jobs:
  install_paper:
    docker:
      - image: debian:bullseye-20210902-slim
    resource_class: medium
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          command: ./build.sh
workflows:
  version: 2
  myworkflow:
    jobs:
      - install_paper
